### PR TITLE
Panopuppet package

### PR DESCRIPTION
**Pull request by gknight007**
Created a panopuppet module.  Moved all scope references to the new module.  Added setup.py so panopuppet can use distutils.

### CODE REVIEW

**Comment by propyless** [comment]
Hi @gknight007 

Theres been some new commits since you started working on this.
Could you rebase all your changes and repush them?

**Comment by propyless** [comment]
@gknight007 got some time to rebase these changes?

**Comment by propyless** [comment]
Have you tested that everything works after the changes? I got some errors with the templates not being able to extend another template since it can't look up the directories

**Comment by propyless** [comment]
```
(panopuppet) PS C:\Users\etaklar\PycharmProjects\panopuppet-public\panopuppet> python .\manage.py
Traceback (most recent call last):
  File ".\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\etaklar\Documents\.virtualenv\panopuppet\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Users\etaklar\Documents\.virtualenv\panopuppet\lib\site-packages\django\core\management\__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "C:\Users\etaklar\Documents\.virtualenv\panopuppet\lib\site-packages\django\conf\__init__.py", line 48, in __getattr__
    self._setup(name)
  File "C:\Users\etaklar\Documents\.virtualenv\panopuppet\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\etaklar\Documents\.virtualenv\panopuppet\lib\site-packages\django\conf\__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\etaklar\Documents\.virtualenv\panopuppet\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'panopuppet'
(panopuppet) PS C:\Users\etaklar\PycharmProjects\panopuppet-
```

**Comment by gknight007** [comment]
Everything worked for me when I tested it.  I do need to modify the install instructions.  Did you install via the setup.py script when you got the "No module named 'panopuppet'"?

**Comment by propyless** [comment]
I do all my "dev" work after just checking out the repo in a folder and running python manage.py runserver. and thats what i can't do anymore. I don't want to have to install it so i can work on it.

**Comment by gknight007** [comment]
You don't have to install panopuppet in order for python to find it.  You can set the python path and include the dev directory while developing.

**Comment by gknight007** [comment]
PR #118 is updated with the latest master branch.

**Pull request closed without merging**
