### PR TITLE
Beautify Facts and adds Debian Jessie install instructions

### PR DESCRIPTION
**Pull request by propyless**
@ap-16 heres your changes to the facts page and also the install instructions for debian jessie!

### CODE REVIEW

**Comment by ap-16** [comment]
original Facts display
json_fact_hash_orig

somewhat more neatly arranged with this patch:
json_fact_hash_beauty

**Comment by propyless** [comment]
Ah right, yes.. I see. This is also something I've been looking at making "prettier" rather than the blob of json code..

Do you think you'll have more time to work on this? Just to for example put for example:
Imagine the below being a table.
```
| OS                        |
|   | family                | Debian
|   | architechture         | amd64
|   | selinux/enabled       | false
|   | distro/id             | Debian
|   | distro/release/minor  | 3
|   | distro/release/major  | 8
|   | distro/release/full   | 8.3
```

**Comment by propyless** [comment]
Heres  my expansion of your PR.
2016-05-05-072613_847x572_scrot

**Comment by propyless** [comment]
2016-05-05-094011_863x487_scrot

**Comment by propyless** [comment]
Changes have been merged.  @ap-16 thank you for your contribution!

**Pull request closed without merging**
