### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by gknight007**

### CODE REVIEW

**Comment by propyless** [comment]
Fantastic! I've rm -rf'd my system to install linux instead of w10 so i'm not able to test your changes at the moment. But as soon as I have I will test these changes immediately! Thanks for rebasing!

**Comment by propyless** [comment]
Alright! Got a gentoo system running. Lets start taking a look at this PR then!

**Comment by propyless** [comment]
Yo,

Still working on this @gknight007. A new season started in Path of Exile so I was sidetracked... but I'm working on erecting a puppetenv so I can test these changes.
Using docker.. wish I didn't but it felt easier for development purposes..
...so I haven't forgotten this.

**Comment by propyless** [comment]
So ... I'm taking way to long with docker and stuff and have not found the time/inspiration to work on it so I'm just going  to use my traditional VM... It will be done this week. Sorry for the delay..

**Comment by propyless** [comment]
Hey there, Alright, So I've changed my paths (all had to do with my IDE settings) and some of the settings its sets by default. But it works now and all the functionality seems to be working and looking at the code, none of the logic seems to be modified in anyway except for being moved.
 but now.. how to move on.. 

So I'm guessing we are going to need some instructions and descriptions over the install process using distutils. Does this unlock the possibility of installing panopuppet via for example pip?
With this I mean, "if installed via distutils, do this do that, config files are now located at "x" instead of y
since you moved config.yaml to /etc/panopuppet for example.

Since I've never used distutils to package anything so I will need some guidance from your side.

Again, very sorry for the unacceptable delay and thank you so much for your hard work and contribution, its a real honour that there are others that are enjoying this product enough to contribute to make it even better!

**Comment by gknight007** [comment]
No problem.  Life happens, I fully understand.  

To really understand the work done, read this doc.  https://docs.python.org/2/install/

In short, all the moving was to allow panopuppet to have a setup.py and a standard module layout/namespace.  

Docs on setup.py for module creators is here, https://docs.python.org/2/distutils/setupscript.html

** INSTALL **
cd $repo_dir; python3 setup.py install

If you want to add panopuppet to pypi (aka allowing it to be installed via pip), you should go here, https://pypi.python.org/pypi.  I have never added myself, but it looks to be as simple as 'python3 setup.py upload'

**Comment by sheijmans** [comment]
Will the README.MD also be updated with a migration to the new layout of panopuppet.
Also some updates to SELinux are needed.

**Comment by propyless** [comment]
It will include it later on. this PR pushes stuff to master so i've done a new PR with some other fixes that pushes it into the dev branch. but before I merge dev -> master the readme will be updated to reflect the latest changes that gknight contributed.

**Comment by propyless** [comment]
Hey @gknight007 the changes are pushed into the dev branch. Once I've updated the docs for the install process I'm going merge dev -> master

**Comment by propyless** [comment]
Please refer to PR #122

**Pull request closed without merging**
