### PR TITLE
Changed markup for RHEL/Centos6, same as for Centos7.

### PR DESCRIPTION
**Pull request by sheijmans**
Changed markup for RHEL/Centos6, same as for Centos7.

### CODE REVIEW

**Comment by propyless** [comment]
@sheijmans this one has conflicts, do you have time to take a peek?

**Comment by sheijmans** [comment]
Think it conflicts with this one:
https://github.com/propyless/panopuppet/commit/ad7c4f30688498c2693432528dbc8de169954b49

Will it be enough if I added that to this PR?
Or checkout the dev branch and then maken the changes for a new PR.

**Comment by propyless** [comment]
checkout dev branch, cherry pick your commit into that branch, it will say that some changes are conflicting and then you can probably just easily fix and push :)

**Comment by sheijmans** [comment]
Created new PR (https://github.com/propyless/panopuppet/pull/135) against dev branch.

**Pull request closed without merging**
